services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/prod/django/Dockerfile
    image: queryzen_prod_django
    environment:
      CELERY_BROKER_URL: redis://redis:6379/1
    ports:
      - '8000:80'
    healthcheck:
      test: [ "CMD", "wget", "-q0-", "http://localhost:80/_healthcheck" ]
      interval: 1m
      timeout: 10s
      retries: 2
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
    depends_on:
      # - postgres
      - redis
    command: [ /start ]

  worker:
    image: queryzen_prod_django
    command: /start-celeryworker
    environment:
      CELERY_BROKER_URL: redis://redis:6379/1
    volumes:
      - ./db.sqlite3:/app/db.sqlite3

  redis:
    image: redis:7.4
    restart: on-failure
    ports:
      - '6379:6379'

  flower:
    image: mher/flower
    environment:
      CELERY_BROKER_URL: redis://redis:6379/1
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    ports:
      - '5555:5555'
    depends_on:
      - worker
      - redis
#    env_file:
#      - ./.envs/.production/.django
#      - ./.envs/.production/.postgres