name: 📦🔌 Build and Release client in Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_SURISTER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SURISTER_PAT }}
      - uses: actions/checkout@v4

      - name: Set VERSION from tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
      - name: Echo Version from tag
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: "queryzen-api/compose/prod/django/Dockerfile"
          context: "queryzen-api/"
          push: true
          tags: |
            surister/queryzen_api:${{ env.RELEASE_VERSION }}
            surister/queryzen_api:latest